# Copyright 2026 Open Source Robotics Foundation, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:private"])

licenses(["notice"])

cc_library(
    name = "fastdds",
    srcs = glob(
        [
            "src/cpp/**/*.h",
            "src/cpp/**/*.hpp",
            "src/cpp/**/*.ipp",
            "src/cpp/**/*.cpp",
            "src/cpp/**/*.cxx",
        ],
    ),
    hdrs = glob([
        "include/**/*.hpp",
        "thirdparty/asio/asio/include/**/*.hpp",
        "thirdparty/asio/asio/include/**/*.ipp",
        "thirdparty/boost/include/**/*.h",
        "thirdparty/boost/include/**/*.hpp",
        "thirdparty/boost/include/**/*.ipp",
        "thirdparty/taocpp-pegtl/**/*.hpp",
    ]) + [
        "thirdparty/filewatch/FileWatch.hpp",
    ],
    cxxopts = [
        "-Wno-deprecated-builtins",
        "-Wno-deprecated-declarations",
        "-Wno-deprecated-literal-operator",
        "-Wno-nonnull",
        "-Wno-thread-safety-analysis",
        "-Wno-unknown-pragmas",
    ],
    includes = [
        "include",
        "src/cpp",
        "src/cpp/utils",
        "thirdparty/asio/asio/include",
        "thirdparty/boost/include",
        "thirdparty/filewatch",
        "thirdparty/taocpp-pegtl",
        "thirdparty/taocpp-pegtl/pegtl",
        "thirdparty/taocpp-pegtl/pegtl/contrib",
        "thirdparty/taocpp-pegtl/pegtl/internal",
    ],
    local_defines = [
        "SQLITE3_SUPPORT=1",
        "TLS_FOUND=1",
        "HAVE_SECURITY=1",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@fastcdr",
        "@foonathan_memory",
        "@nlohmann_json//:singleheader-json",
        "@openssl",
        "@sqlite3",
        "@tinyxml2",
    ],
)
